name: Pull Request Build Check

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Lint & Build
    uses: ./.github/workflows/build.yml